blank_issues_enabled: false
contact_links:
  - name: Contribution guidelines
    url: https://github.com/OscarAkaElvis/asleap/blob/dev/CONTRIBUTING.md
    about: Read the contribution and issue creation policies before opening an issue.
